### ISSUE TITLE
Toggle view buttons and other features not showing

### ISSUE THREAD

**Issue by proteusblack** [selfire1/obsidian-you-theme#12]
In the new update, I cannot find any way to access a toggle for live preview / reading view. The floating button is gone but if I understand correctly, there should be a button on the title bar. My title bars have no buttons, only the title itself. I don't see any options about this in the style settings plugin, only colors and fonts.

**Comment by selfire1** [comment]
This should be fixed in [1.0.1](https://github.com/selfire1/obsidian-you-theme/releases/tag/1.0.1). Would you mind updating the theme and trying again?

**Comment by proteusblack** [comment]
I'm noticing that when all the style settings are disabled, the floating view toggle shows in its normal place. If they are enabled, then nothing shows up.
