### ISSUE TITLE
Feature Request: Customizable Page Header support 

### ISSUE THREAD

**Issue by perfidopelato** [selfire1/obsidian-you-theme#14]
Could you please expand support for the plug-in Customizable Page Header showing several buttons?

**Comment by selfire1** [comment]
Hi! Could you expand on what you mean? You can add multiple buttons. The first is shown in the FAB, the other in headers. When adding new buttons, you might need to refresh Obsidian.

![Screenshot_20220225-185418.jpg](https://user-images.githubusercontent.com/70809675/155720625-1f294249-9e46-4b14-923a-db6985dba59c.jpg)

**Comment by perfidopelato** [comment]
OK, sorry, this is related to Issue #13 : on iPhone 13 Pro I can't see the editor header at all.

**Comment by selfire1** [comment]
Duplicate to #13
