### ISSUE TITLE
Edit/Preview Buttons missing

### ISSUE THREAD

**Issue by SpxterWohlf** [selfire1/obsidian-you-theme#20]
My edit and preview buttons are just missing on desktop and mobile for some reason, I am using the latest version of the theme as well as Obsidian (v0.14.2) and I also tried installing the customizable page and header plugin:

![Screenshot_20220405-235109](https://user-images.githubusercontent.com/33076633/161898977-6d379835-db25-40f0-a57c-7684f00a2c80.png)

On desktop I have a greyed out square:
![image](https://user-images.githubusercontent.com/33076633/161899031-92cb72c0-5550-47e7-b9f9-1e47787fdf55.png)

**Comment by selfire1** [comment]
Hi! Could you let me know which setting you have enabled in Style Settings?

**Comment by SpxterWohlf** [comment]
Hi @selfire1 

The cause of this issue was from another program that was broken and adjusted how the header buttons worked.

I am closing this because it was not a issue with the theming
