### ISSUE TITLE
Awkward blockquote rendering

### ISSUE THREAD

**Issue by midnightmercenary** [selfire1/obsidian-you-theme#21]
Line breaks in block quotes creates this weird looking extra "bubble." Could this be fixed?
![Screenshot_20220423-132251_Obsidian](https://user-images.githubusercontent.com/56935282/164917006-ec2fe755-54e4-45c7-ab6b-bbff22d6b1a6.jpg)

Best theme for mobile. Love it on my Galaxy Note20U.

**Comment by midnightmercenary** [comment]
I should of added that this only occurs in Live Preview mode. In reading mode,  it renders as one bubble/blockquote just fine.

**Comment by selfire1** [comment]
Hi! Thanks for commenting. I'll have a look at that!

**Comment by midnightmercenary** [comment]
That's too bad. I certainly enjoyed the look! Hopefully Obsidian considers a change to support a visual feature like this and I look forward to the next release. Thanks for all your hard work.
