### ISSUE TITLE
Support iOS safe area insets

### ISSUE THREAD

**Issue by ankushg** [selfire1/obsidian-you-theme#3]
The Obsidian You theme doesn't properly support iOS Safe Area insets

Minimal does though, so maybe there's some stuff from their CSS which may be useful!

<details>
  <summary>Screenshots in here!</summary>
  
|         | Minimal                                                                                                                     | Obsidian You                                                                                                                                          |
|---------|-----------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| Sidebar | ![IMG_E0E61C644348-1](https://user-images.githubusercontent.com/227041/140161958-519afada-8d05-4c55-8809-75ca7f7f6ba7.jpeg) | ![CFF3AA12-1AE4-46FF-A241-AA5C0BFC1DB2_1_105_c](https://user-images.githubusercontent.com/227041/140152550-fc05c6f9-af73-4f9e-a17a-eb78a4408bf5.jpeg) |
| Text    | ![IMG_A9016EE0AC02-1](https://user-images.githubusercontent.com/227041/140162169-e6f83f8f-4b6a-4156-83df-3b27656de612.jpeg) | ![9F742B4F-AE5F-409D-9E76-D393F2AFA7BC_1_105_c](https://user-images.githubusercontent.com/227041/140152590-29512609-1d71-4e72-a9e4-5d1cbf1b1f31.jpeg) |
|         |                                                                                                                             |                                                                                                                                                       |
</details>

**Comment by selfire1** [comment]
Hi! Thanks for letting me know. Since I don't use an iPhone it's a bit hard for me to debug but I'm working on it!

**Comment by selfire1** [comment]
Note to self: Having a look at https://github.com/mgmeyers/obsidian-california-coast-theme/blob/main/src/010-main.css and searching for `safe-area` might also be relevant.

**Comment by selfire1** [comment]
Shipped in [0.1.5](https://github.com/selfire1/obsidian-you-theme/releases/tag/0.1.5)
