### ISSUE TITLE
Some Selectors break when not using English

### ISSUE THREAD

**Issue by phibr0** [selfire1/obsidian-you-theme#5]
Your selectors are sometimes based on aria-labels, which contents might change with other Languages.

Here is one example:
https://github.com/selfire1/obsidian-you-theme/blob/d4eaf70e3431da7c9dbc1863b6a7c306d29f3e24/obsidian.css#L807-L811

**Comment by selfire1** [comment]
Thank you for bringing this to my attention! I haven't been able to find a solution not involving labels yet. I am still tinkering in a branch. For now, I have just added the German names to the label – which I think were the ones relevant for you.

If you have an idea how to drop the use of labels all together, please let me know!

PS: There is a plugin which I haven't tried: [yszk0123/obsidian-floating-action-button](https://github.com/yszk0123/obsidian-floating-action-button) that adds the same functionality.
