### ISSUE TITLE
Make hiding title action button optional (via Style Settings)

### ISSUE THREAD

**Issue by tctco** [selfire1/obsidian-you-theme#8]
First of all, great work! However, it seems that there is no `more options` button? I wonder if there is a button that allows you to split the current panel to do some other operations in the `more options` menu?

**Comment by selfire1** [comment]
Hi and thank you!

![Screenshot_20211113-120913~2.jpg](https://user-images.githubusercontent.com/70809675/141631076-67b962b7-05c6-4026-8ba0-3b10de55f7cb.jpg)

Are you referring to this button? To simplify the limited space on mobile, the button is hidden. You can access all options through the command pallete (pulling down on mobile).

If this remains a pain point for you though, I might add an option to toggle the display.

**Comment by tctco** [comment]
Yes, that's exactly what I mean (forgive me for my bad English since I'm not a native speaker)! I'm using the 'pulling down on mobile' to open a random note, so it would be great to keep that button <3

**Comment by selfire1** [comment]
Alright, thanks for clarifying! No worries about language, English isn't my mother tongue either :)

I'll work on that for some upcoming releases!

**Comment by selfire1** [comment]
Hi @tctco! Now in [0.1.4](https://github.com/selfire1/obsidian-you-theme/releases/tag/0.1.4) you can toggle the title bar menu in Style Settings. I just realised now that might not be what you're after though 🤔 

Would you mind updating the theme and letting me know if this solves it?

**Comment by tctco** [comment]
Hi, sorry about the late reply. Too many exams these days TAT

I think I've downloaded the latest version of the obsidian you theme and the style settings plugin via the obsidian theme/plugin store, but I don't see any option to turn the button on. I don't know what goes wrong :(

**Comment by selfire1** [comment]
No worries! Would you just mind mentioning again which button you're looking for? The one in the title bar or the one in the right sidebar?

For now, I'd recommend you install [customizable page header buttons](https://github.com/kometenstaub/customizable-page-header-buttons) and simply add a button to the command palette!

**Comment by tctco** [comment]
I'm using onedrive to sync my notes and I sometimes split panes on my PC. However, if I forget to close the additional panes and sync files on my phone, I could not find a way to close them with the `obsidian you` theme. And I may need to turn on functions like `toggle backlinks in document` (though I think this should be turned on by default), so it would be convenient for me to have an option to keep the `more options` button on the title bar.

The plugin you recommended works pretty well. Thx :)

**Comment by selfire1** [comment]
Since the plugin works, I'll close this for now :)
